version: '3'
networks:
    app_net:
services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
            - app
        container_name: project_nginx
        networks:
            - app_net

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: project_app
        networks:
            - app_net

    db:
        image: mysql:8.3.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: kolizey
            MYSQL_USER: admin
            MYSQL_PASSWORD: C5oQwX
            MYSQL_ROOT_PASSWORD: "_q0H35Q3cc.k"
        ports:
            - "8801:3306"
        command: "mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password"
        container_name: project_db
        networks:
            - app_net
